services:
  db:
      image: postgres
      environment:
        POSTGRES_USER: xie
        POSTGRES_PASSWORD: 111
        POSTGRES_DB: zoodb
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "xie"]
        interval: 5s
        timeout: 5s
        retries: 5


  frontend:
    build: ./reactfrontend
    ports:
      - "3000:3000"


  backend_django:
    build: ./Django Backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy