# Generated by Django 5.1.2 on 2024-11-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookdata",
            old_name="name",
            new_name="title",
        ),
    ]
