# Generated by Django 5.1.2 on 2025-02-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('size', models.CharField(max_length=100)),
                ('climate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50, unique=True)),
                ('diet', models.CharField(max_length=100)),
                ('lifespan', models.PositiveIntegerField()),
                ('behaviour', models.CharField(max_length=500)),
                ('habitat', models.ManyToManyField(to='system.habitat')),
            ],
        ),
    ]
