# Generated by Django 5.1.2 on 2025-03-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zookeeper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("qualifications", models.TextField()),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("FEEDING", "Feeding"),
                            ("MEDICAL", "Medical"),
                            ("CLEANING", "Cleaning"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("scheduled_time", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="system.animal"
                    ),
                ),
                (
                    "zookeeper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system.zookeeper",
                    ),
                ),
            ],
        ),
    ]
