# Generated by Django 5.1.2 on 2025-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_zookeeper_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zookeeper",
            name="qualifications",
        ),
        migrations.AddField(
            model_name="zookeeper",
            name="role",
            field=models.CharField(
                choices=[
                    ("L1", "Level1"),
                    ("L2", "Level2"),
                    ("L3", "Level3"),
                    ("admin", "Admin"),
                ],
                default="L1",
                max_length=10,
            ),
        ),
    ]
