# Generated by Django 5.1.2 on 2025-03-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0004_membership_visitor_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="duration",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="visitor",
            name="membership_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="membership_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EventFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="system.event"
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="system.visitor"
                    ),
                ),
            ],
        ),
    ]
