# Generated by Django 5.1.2 on 2025-03-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0005_membership_duration_visitor_membership_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="attend",
        ),
        migrations.RemoveField(
            model_name="event",
            name="price",
        ),
        migrations.AddField(
            model_name="event",
            name="memberships",
            field=models.ManyToManyField(related_name="events", to="system.membership"),
        ),
    ]
