# Generated by Django 5.1.2 on 2025-03-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0006_remove_event_attend_remove_event_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitor",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="last_login",
        ),
        migrations.AlterField(
            model_name="visitor",
            name="password",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
