# Generated by Django 5.1.2 on 2025-03-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0007_remove_visitor_is_active_remove_visitor_last_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="password",
            field=models.CharField(max_length=200),
        ),
    ]
