# Generated by Django 5.1.2 on 2025-03-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0008_alter_visitor_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "duration",
                    models.DurationField(help_text="Duration in format HH:MM:SS"),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("available_spots", models.PositiveIntegerField(default=20)),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "animals",
                    models.ManyToManyField(related_name="tours", to="system.animal"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="system.tour",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_feedback",
                        to="system.visitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "habitat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="system.habitat"
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="system.tour"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("tour", "order")},
            },
        ),
        migrations.AddField(
            model_name="tour",
            name="route",
            field=models.ManyToManyField(
                related_name="tours", through="system.TourRoute", to="system.habitat"
            ),
        ),
    ]
