# Generated by Django 5.1.2 on 2025-03-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0009_tour_tourfeedback_tourroute_tour_route"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="animals",
        ),
    ]
